/**
 * Generated by vite-plugin-z3.
 * This file provides type-safe handles to your Z3 workers.
 */
import { createZ3Worker, solveWith } from "@sigmasd/vite-plugin-z3/runtime";

/**
 * Worker handle for 'scheduler-worker.js'.
 */
export const schedulerWorker = {
  /** Public URL to the bundled worker */
  url: "/scheduler-worker.js",
  /** Run a solve task and terminate immediately */
  // deno-fmt-ignore
  // deno-lint-ignore no-explicit-any
  run: <T = any>(data: any): Promise<T> => solveWith("/scheduler-worker.js", data),
  /** Create a long-lived worker instance. Don't forget to .terminate()! */
  create: () => createZ3Worker("/scheduler-worker.js"),
};
